// <auto-generated />
namespace PublicServicesDomain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class decimalmoney : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(decimalmoney));
        
        string IMigrationMetadata.Id
        {
            get { return "202011261437282_decimal money"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
