// <auto-generated />
namespace PublicServicesDomain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class intinprevandcurindication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intinprevandcurindication));
        
        string IMigrationMetadata.Id
        {
            get { return "202012042139544_int in prev and cur indication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
